### ISSUE TITLE
; is not a valid sentence delimiter

### ISSUE THREAD

**Issue by balmas** [perseids-project/llt-segmenter#1]
@nevenjovanovic requests that we treat ; like , and not deem it to be a sentence delimiter

**Comment by nevenjovanovic** [comment]
Some additional information to what @balmas wrote may be helpful: I suggest a change made to the _Latin_ tokenizer; the semicolon (;) seems to me to have functions similar to the comma -- sometimes it marks the end of a sentence or clause, sometimes not. If we are not making guesses about clause ends in the case of comma, we should not make it in the case of semicolon. And, finally, at least around these parts, people don't expect a Latin sentence to end on a semicolon; it would have a full stop if it needed to end.
Of course, if there is a strong treebanking argument on why we want to split a sentence on a semicolon, I'll gladly accept that and explain it to my students.

**Comment by balmas** [comment]
consensus is generally no change for Greek, drop the semicolon as delimiter for Latin, with a wishlist item of making this configurable.

**Comment by nevenjovanovic** [comment]
Agree absolutely.

**Comment by balmas** [comment]
One last question @nevenjovanovic -- do we want to automatically annotate it as AuxX as we do for commas?

**Comment by nevenjovanovic** [comment]
@balmas -- yes, I would treat the semicolon as a punctuation mark automatically.

**Comment by balmas** [comment]
@nevenjovanovic this is deployed now. Just be sure to refresh your browser on the treebank input form page to get the latest code. It will now default to NOT using the semicolon as a delimiter for Latin texts (as long as the Latin language option is properly selected).  You can override this by opening the advanced options and checking or unchecking the Semicolon delimiter option before submitting. Let me know if you have any problems with the changed behavior.
